### ISSUE TITLE
Select Dataset: Finance and Contracts

### ISSUE THREAD

**Issue by waldoj** [sunlightpolicy/State-Open-Data-Census#10]
Select the one dataset that serves as the touchstone of state-level finance and contracts data.

**Comment by waldoj** [comment]
I think agency checkbooks are the top dataset here. It's transaction-level data, within the state's power to capture and republish, it continues the financial open data trend of the late '00s (with data that was often just Excel spreadsheets or HTML tables, and hasn't been modernized since), and it's enormously useful. There are no widely used open data standards for contracts, procurement processes, or RFPs, which functionally rules them out. While the same is true for checkbooks, they're so easy that the lack of standards isn't much of an obstacle.

**Comment by emily878** [comment]
:+1:
