### ISSUE TITLE
Select Dataset: Energy and Environment

### ISSUE THREAD

**Issue by waldoj** [sunlightpolicy/State-Open-Data-Census#11]
Select the one dataset that serves as the touchstone of state-level energy and environment data.

**Comment by emily878** [comment]
I received a request for "Environmental Permits" to be the core dataset in this category.

**Comment by waldoj** [comment]
Task for Waldo: figure out how we can define "environmental permits." What kind of data does that encompass?

**Comment by waldoj** [comment]
Air, water, and waste permits seem to be the three most common kinds. There are others administers by various state environmental agencies that are far from universal—burning, coal mining, uranium mining, hard rock mining, "opencut" mining, solid waste management, storage tanks, septic tanks, stormwater, small-scale renewable energy, biosolids application...actually, it looks like I could go on for a while. Broadly, it seems to break down to water, air, land, and waste permits.

Perhaps this is a good dataset to keep really broad. I suggest just say "environmental permitting data," and leave it up to states' norms—what is and is not part of their environmental portfolio—as to what that encompasses.

**Comment by waldoj** [comment]
In the spirit of `WP:BOLD`, I'll close this and open up a new issue to act on it.
