### ISSUE TITLE
Select Dataset: Earth Observation

### ISSUE THREAD

**Issue by waldoj** [sunlightpolicy/State-Open-Data-Census#12]
Select the one dataset that serves as the touchstone of state-level Earth observation data. Or, possibly, select a couple of datasets, this this is really a grab-bag category.

Also, rename "Earth Observation," because it doesn't describe what we want it to describe. See [the list of Earth observation datasets](https://github.com/sunlightpolicy/State-Open-Data-Census/blob/master/Data/state%20open%20datasets%20-%20Sheet1.tsv) to get the idea.

**Comment by emily878** [comment]
State-owned land, ideally GIS.
