### ISSUE TITLE
Select Data: Crime and Justice

### ISSUE THREAD

**Issue by waldoj** [sunlightpolicy/State-Open-Data-Census#13]
Select the one dataset that serves as the touchstone of state-level crime and justice data.

**Comment by waldoj** [comment]
This is hard, because incident data is generally (always?) _local_ data. It's often not within the state's power to collect this data.

**Comment by emily878** [comment]
It would be GREAT if this was a court dataset. How about supreme court decisions, or appeals court decisions?

**Comment by waldoj** [comment]
Everybody would get an F, and no state would have the power to make their courts improve their data.

**Comment by emily878** [comment]
Of course corrections data would also be useful. I'll bet there's more precise counts available at the state level than what gets collected federally.

**Comment by emily878** [comment]
(Sorry! Hit "close" by accident.)

**Comment by emily878** [comment]
Incarceration data.
