### ISSUE TITLE
Select Dataset: Economic Development

### ISSUE THREAD

**Issue by emily878** [sunlightpolicy/State-Open-Data-Census#15]
Select the one dataset that serves as the touchstone of state-level economic development data.

**Comment by waldoj** [comment]
I don't feel like any of our [example economic development datasets](https://github.com/sunlightpolicy/State-Open-Data-Census/blob/master/Data/state%20open%20datasets%20-%20Sheet1.tsv) are particularly great:
- land use maps
- subsidies
- local planning and zoning meetings notices
- real estate holdings
- surplus real estate and property

OTOH, it's a narrow topic. Among these choices, I think "subsidies" strikes me as the most promising, more so if it includes both _provided_ subsidies (_here's who's getting money_) and _available_ subsidies (_here's what we're willing to subsidize_).

**Comment by emily878** [comment]
Yeah, state tax expenditures/grant programs would be my top choice. We could get input from Good Jobs First on ideal examples.
