### ISSUE TITLE
Select Dataset: Statistics

### ISSUE THREAD

**Issue by emily878** [sunlightpolicy/State-Open-Data-Census#19]
Select the one dataset that serves as the touchstone of state-level statistics data.

**Comment by waldoj** [comment]
This seems like a weird domain to me. All of the others are topical. Statistics is data about _other_ topics. This category might should be jettisoned.

**Comment by emily878** [comment]
I _almost_ agree, except we need a spot for demographics. I know the US Census is a convenient spot for this, but a lot of states do municipal population projections that are pretty useful.
