### ISSUE TITLE
Select Dataset: Geospatial

### ISSUE THREAD

**Issue by waldoj** [sunlightpolicy/State-Open-Data-Census#9]
Select the one dataset that serves as the touchstone of state-level geospatial data.

**Comment by waldoj** [comment]
I think address points is the representative dataset here. Although these are almost aways the product of localities, most states aggregate them, and there's huge momentum to make that universal. I _wish_ parcel maps could be the representative dataset, but  we have to walk before we can run. I think human geography is more useful than natural geography (e.g., topography, soil types, rivers & streams, etc.). Road data is probably more useful, but that's a solved problem—every state would get an 100% rating. Best to go with address points.

**Comment by emily878** [comment]
:+1:
